apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodeangular
  namespace: nodeangular
  labels:
    app: nodeangular
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::944627734564:policy/devops_admin